import { BatteryCharging, BatteryMedium, ChevronRight, Clock3, Smartphone } from "lucide-react";
import { Link } from "react-router-dom";
import type { Device } from "../types";
const ago = (date: string) => { const mins = Math.floor((Date.now() - new Date(date).getTime()) / 60000); return mins < 1 ? "Just now" : mins < 60 ? `${mins}m ago` : `${Math.floor(mins/60)}h ago`; };
export function DeviceCard({ device }: { device: Device }) {
  const online = device.status === "online" && Date.now() - new Date(device.lastSeenAt).getTime() < 10 * 60_000;
  const granted = device.permissions.filter(p => p.status === "granted").length;
  return <Link to={`/devices/${device._id}`} className="group card border border-base-300 bg-base-100 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="card-body gap-5"><div className="flex items-start justify-between"><div className="flex items-center gap-4"><div className="grid size-14 place-items-center rounded-2xl bg-primary/10 text-primary"><Smartphone size={26}/></div><div><h3 className="text-lg font-extrabold">{device.childName}</h3><p className="text-sm text-base-content/50">{device.deviceName}</p></div></div><span className={`badge gap-1.5 border-0 ${online ? "badge-success text-white" : "badge-ghost"}`}><span className={`size-1.5 rounded-full ${online ? "bg-white animate-pulse" : "bg-base-content/30"}`}/>{online ? "Online" : "Offline"}</span></div><div className="grid grid-cols-3 gap-2 rounded-2xl bg-base-200/70 p-3 text-center"><div><p className="text-xs text-base-content/45">Battery</p><p className="mt-1 flex items-center justify-center gap-1 text-sm font-bold">{device.isCharging ? <BatteryCharging size={15}/> : <BatteryMedium size={15}/>} {device.batteryLevel ?? "—"}{device.batteryLevel != null && "%"}</p></div><div className="border-x border-base-300"><p className="text-xs text-base-content/45">Access</p><p className="mt-1 text-sm font-bold">{granted}/{device.permissions.length || 3}</p></div><div><p className="text-xs text-base-content/45">Last sync</p><p className="mt-1 flex items-center justify-center gap-1 text-sm font-bold"><Clock3 size={14}/>{ago(device.lastSeenAt)}</p></div></div><div className="flex items-center justify-between text-sm font-bold text-primary"><span>View device details</span><ChevronRight className="transition group-hover:translate-x-1" size={18}/></div></div></Link>;
}
